### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by natcl** [eazel7/tingo-red#1]
Hello I tried this node and the json document never seems to be created on disk, do you have an exemple flow that show how it works ?

**Comment by eazel7** [comment]
oh... mmm I'll create one

**Comment by eazel7** [comment]
In the meantime, did you set the path on the configuration node?

**Comment by natcl** [comment]
yes tried different combinations of relative/absolute paths but not file seems to get created.


--
lecaude.com 
studioimaginaire.com

**Comment by eazel7** [comment]
https://www.youtube.com/watch?v=eMdHiMjdGXQ here is a mini demo

**Comment by eazel7** [comment]
oops! I uploaded the wrong video!

**Comment by eazel7** [comment]
@natcl https://youtu.be/Ice3myP99VI < this is the good one

**Comment by natcl** [comment]
Haa thanks path needs to be a folder, thought it needed to be a file.
Works thanks !

2018-02-07 20:08 GMT-05:00 Diego Perez <notifications@github.com>:

**Comment by natcl** [comment]
Was wondering for the update node, wouldn't it be more simple if the
predicate was passed using msg.topic and the update operation using
msg.payload ?

2018-02-07 20:45 GMT-05:00 Diego Perez <notifications@github.com>:

**Comment by eazel7** [comment]
@natcl AFIK the topic is a string, I've always seen it being a string in all samples. Although it might be supported, I'd rather continue being explicit about it.
Feel free to fork or make a poll!

**Comment by natcl** [comment]
It can be anything but it’s true that in an inject mode it’s only exposes as a string. probably better to leave msg.predicate as is but perhaps use msg.payload to update ?


--
lecaude.com 
studioimaginaire.com

**Comment by eazel7** [comment]
that makes sense. I'll publish v1.1.0 next week with that change and a 
find-one node
